### ISSUE TITLE
一点小建议及时间显示问题

### ISSUE THREAD

**Issue by 1621391916** [iyear/E5SubBot#1]
1.机器人查看账户信息的时候能否显示所有日志?或者把日志log在服务器里
2.tg里显示的调用时间好像不是北京时间
3.建议调用间隔改成随机，太规律容易被发现

**Comment by iyear** [comment]
1.马上有v0.1.1，主要是用户反馈加强，每次完成后会向所有用户发送结果。至于log待我研究一下，以后会有完整日志
2.时间是根据运行环境决定的，如果要北京时间，把服务器时区改成Asia/Shanghai
3.会考虑，但这与cron的目的有些不相符，而且微软对调用api的频次没有做出很大限制

1621391916 <notifications@github.com> 于2020年4月1日周三 下午3:32写道：

**Comment by 1621391916** [comment]
服务器时区改了为什么还是不对
![image](https://user-images.githubusercontent.com/42343279/78115172-f671dc80-7434-11ea-9aa2-54806f45c5f2.png)
![image](https://user-images.githubusercontent.com/42343279/78115313-320ca680-7435-11ea-9c90-d0f35e1a6e65.png)

**Comment by iyear** [comment]
> 服务器时区改了为什么还是不对
> ![image](https://user-images.githubusercontent.com/42343279/78115172-f671dc80-7434-11ea-9aa2-54806f45c5f2.png)
> ![image](https://user-images.githubusercontent.com/42343279/78115313-320ca680-7435-11ea-9c90-d0f35e1a6e65.png)

最近更新时间为最近调用的时间，等待下一次Task后就可以了

**Comment by 1621391916** [comment]
> > 服务器时区改了为什么还是不对
> > ![image](https://user-images.githubusercontent.com/42343279/78115172-f671dc80-7434-11ea-9aa2-54806f45c5f2.png)
> > ![image](https://user-images.githubusercontent.com/42343279/78115313-320ca680-7435-11ea-9c90-d0f35e1a6e65.png)
> 
> 最近更新时间为最近调用的时间，等待下一次Task后就可以了

刚刚试了一下，要重新启动进程才能正常显示时间

**Comment by iyear** [comment]
好的，那就没问题了

1621391916 <notifications@github.com> 于2020年4月1日周三 下午4:43写道：
