### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by BA7JCM** [iyear/E5SubBot#14]
直接在命令行执行，跑不起来，提示“【E5Sub】2021/05/10 13:30:25 main.go:132: http.Post failed: Post https://api.telegram.org/bot1878110893:AAEP57mATZAicmlCyUoCl4yQ2H5qyVinUj0/getMe: dial tcp 108.160.165.147:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.”，但是我把报错里面的那个网址复制出来在浏览器粘贴，能访问，显示“{"ok":true,"result":{"id":1878110893,"is_bot":true,"first_name":"E5_BA7JCM_TEST","username":"ba7jcm_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false}}”

完整运行日志我输出到这个txt里了：
[1.txt](https://github.com/iyear/E5SubBot/files/6449823/1.txt)

**Comment by iyear** [comment]
本地网络问题导致访问超时或失败，看一下有没有设置socks5

**Comment by BA7JCM** [comment]
> 本地网络问题导致访问超时或失败，看一下有没有设置Bot配置socks5
> 很有可能本地开着代理，浏览器走代理过，但是Bot并不会默认走代理，这需要手动配置
> 注意修改BotToken，已经暴露了

我的确是挂了代理（翻了墙），但不知道要怎么设置，关于代理，我手头上有的参数只有一条v2ray的订阅链接

**Comment by iyear** [comment]
在 https://github.com/iyear/E5SubBot#configuration 使用socks5参数设置Bot代理。
找到本地代理socks IP和端口填入配置文件，重启Bot即可

如果在远程机上需要重新搭建一遍环境

**Comment by BA7JCM** [comment]
> 在 https://github.com/iyear/E5SubBot#configuration 使用socks5参数设置Bot代理。
> 找到本地代理socks IP和端口填入配置文件，重启Bot即可
> 
> 如果在远程机上需要重新搭建一遍环境

我试过填这个，也报错，好像说是什么不支持的协议什么的，后来我找朋友帮忙，用它租的在香港的服务器完成了部署……

**Comment by BA7JCM** [comment]
> 本地网络问题导致访问超时或失败，看一下有没有设置Bot配置socks5
> 很有可能本地开着代理，浏览器走代理过，但是Bot并不会默认走代理，这需要手动配置
> 注意修改BotToken，已经暴露了

另外感谢提醒，已更新BotToken，再就是能否考虑代理默认按照本机的代理设置，就像浏览器一样，这样在国内的机子上电脑自己出墙之后就可以不用管机器人自身的网络问题了，让机器人跟着整台电脑一起出墙

**Comment by iyear** [comment]
> > 本地网络问题导致访问超时或失败，看一下有没有设置Bot配置socks5
> > 很有可能本地开着代理，浏览器走代理过，但是Bot并不会默认走代理，这需要手动配置
> > 注意修改BotToken，已经暴露了
> 
> 另外感谢提醒，已更新BotToken，再就是能否考虑代理默认按照本机的代理设置，就像浏览器一样，这样在国内的机子上电脑自己出墙之后就可以不用管机器人自身的网络问题了，让机器人跟着整台电脑一起出墙

可以考虑在下个版本添加
目前还只有socks协议，如果用的http协议不行
