### ISSUE TITLE
自动执行任务报错但没提示

### ISSUE THREAD

**Issue by BA7JCM** [iyear/E5SubBot#16]
我今天突然想起来去看看机器人的日志，发现自动执行的全都大量报错“control.go:156: Send Result ERROR:  api error: Unauthorized (401)”和“ control.go:109: api error: Unauthorized (401)”，但是机器人发给我的结果却显示没有出错的账号，如图所示：
![image](https://user-images.githubusercontent.com/79561519/120938271-7768ea00-c744-11eb-9b0a-678541d9621e.png)
但是我手动执行任务的时候却又没有报错，如图：
![image](https://user-images.githubusercontent.com/79561519/120938401-1d1c5900-c745-11eb-81a1-dd01b90b2da1.png)
不知道这是什么情况

**Comment by iyear** [comment]
这个错误是Bot发送信息至用户的错误，属于Telegram ERROR中的一个错误，并非Bot本身运行的错误。如果一切正常可以不理会

https://core.telegram.org/api/errors#401-unauthorized

大概率是因为发送对象销号，而Bot依旧按照TG ID发送导致的
