### ISSUE TITLE
0.3.0 预发布版本 bot被用户blocked问题

### ISSUE THREAD

**Issue by xbclub** [iyear/E5SubBot#18]
当用户在微软控制台手动禁用bot时 bot发送请求会返回以下日志：
```
{"L":"ERROR","T":"2021-07-07T02:57:58.269Z","C":"bots/sender.go:76","M":"failed to send msg","error":"api error: bot was blocked by the user (401)","id":"xxxxxxxxxxx"}
```
但是此异常并未进入bot的失败列表，多次失败无法成功解绑。

**Comment by iyear** [comment]
这不会进入失败列表，因为这是发送反馈时的错误而非执行任务时的错误，bot只记录执行错误

**Comment by xbclub** [comment]
所以当用户block bot时也应当按照错误进行处理，建议进行解绑操作。

**Comment by iyear** [comment]
> 所以当用户block bot时也应当按照错误进行处理，建议进行解绑操作。

许多用户block bot只是不想收到定时信息，并非不想执行任务
