### ISSUE TITLE
我的第二次续订失败了

### ISSUE THREAD

**Issue by hiifong** [iyear/E5SubBot#32]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Dimlitter** [comment]
@hiifong 请仔细查看readme，项目并不保证续订效果

**Comment by hiifong** [comment]
确实很玄学

**Comment by hiifong** [comment]
谢谢

**Comment by iyear** [comment]
该项目并不保证续订效果，仅用于调用API
