### ISSUE TITLE
 授权后没有跳转页面而是显示错误

### ISSUE THREAD

**Issue by XYZliang** [iyear/E5SubBot#33]
您好，按照步骤5：
`授权后会跳转至http://localhost/e5sub…… (会提示网页错误，复制链接即可)`
发送client_id(空格)client_secret后打开授权连接，登录后没有跳转而是显示错误页面，没有对应的http://localhost/e5sub?code=**
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/59312540/166875456-9c8c4df3-fc76-4ea1-8baf-aac86c9f6414.png">

**Comment by Dimlitter** [comment]
出现这种情况的原因大概率是你使用了`快速启动通道`

请按照`pdf教程`操作，忽视bot链接。

**Comment by dylanbai8** [comment]
遇到了同样的问题，请问怎么解决的呀

**Comment by iyear** [comment]
> 遇到了同样的问题，请问怎么解决的呀

进入Telegram Group 找到置顶PDF，根据操作进行绑定

**Comment by dylanbai8** [comment]
感谢回复，已搞定。

简而言之就是 "手动创建应用"取代"bot自动创建应用" 即可解决问题。

pdf教程有点复杂了，其实只需要手动创建应用后拿到 “client_id+空格+client_secret” 就行了，配置权限那步个骤仍然可以通过bot指引完成。

**Comment by Suwmlee** [comment]
这个问题是配置的时候，在 Redirect URIs 里没有配置 `localhost` 跳转

增加一个 http://localhost/e5sub 的 web 跳转就好了
