### ISSUE TITLE
Docker 起不来

### ISSUE THREAD

**Issue by ixmu** [iyear/E5SubBot#35]
stdout:   ______ _____ _____       _     ____        _   
stdout:  |  ____| ____/ ____|     | |   |  _ \      | |  
stdout:  | |__  | |__| (___  _   _| |__ | |_) | ___ | |_ 
stdout:  |  __| |___ \\___ \| | | | '_ \|  _ < / _ \| __|
stdout:  | |____ ___) |___) | |_| | |_) | |_) | (_) | |_ 
stdout:  |______|____/_____/ \__,_|_.__/|____/ \___/ \__|
stdout: 
stdout: 【E5Sub】2022/06/14 23:14:35 main.go:76: Read Config……
stdout: 【E5Sub】2022/06/14 23:14:35 main.go:94: Connect MySQL Success!
stdout: 【E5Sub】2022/06/14 23:14:35 main.go:96: dial tcp :0: connect: connection refused

**Comment by GreenTeodoro839** [comment]
@ixmu 检查mysql是否可以连上

**Comment by ixmu** [comment]
> @ixmu 检查mysql是否可以连上

用的sqlite，貌似是什么工具无法连接，布吉岛我就不好配置防火墙了

**Comment by GreenTeodoro839** [comment]
@ixmu 用sqlite请删除mysql相关配置

**Comment by ixmu** [comment]
> @ixmu 用sqlite请删除mysql相关配置

bot_token: 2008472516:AAGnRqQo_0QfhpVs3gHAd3N7LPTb98
bindmax: 999
goroutine: 20
admin: 590778346,590778345
errlimit: 999
notice: |-
  aaa
  bbb
  ccc
cron: "1 */1 * * *"
db: sqlite
table: users
sqlite:
  db: data.db

同样的配置文件，使用二进制运行就没毛病

**Comment by GreenTeodoro839** [comment]
@ixmu sqlite不依赖网络，检查你的vps是否可以访问微软

**Comment by ixmu** [comment]
> 

网络运行正常， 仅仅是docker不行，这个提示像极了某些ip被阻断
