### ISSUE TITLE
关于编译/二进制文件的建议

### ISSUE THREAD

**Issue by feilongproject** [iyear/E5SubBot#4]
1. 我用的最新版的二进制文件（linux），在arm64平台上无法运行。希望能增加各个平台的二进制文件（虽然能编译吧）

2. 然后我根据README上的教程编译后，用`go build main.go`，报错：
`# command-line-arguments
./main.go:50:23: undefined: bStart
./main.go:51:20: undefined: bMy
./main.go:52:22: undefined: bBind1
./main.go:53:24: undefined: bUnBind
./main.go:54:24: undefined: bExport
./main.go:55:22: undefined: bHelp
./main.go:56:24: undefined: bOnText
./main.go:58:22: undefined: bTask
./main.go:59:21: undefined: bLog
./main.go:64:40: undefined: SignTask
./main.go:64:40: too many errors`
我在网上搜了一下，好像用`go build *.go`就可以通过go语言编译了，希望能在readme里能改正一下（我不懂go语言，如有出错望指正）

**Comment by iyear** [comment]
@feilongproject 1.0.18会增加
2.本地的README已经改了还没push

**Comment by iyear** [comment]
@feilongproject https://github.com/iyear/E5SubBot/releases 已添加
