### ISSUE TITLE
docker-compose.yml mysql should not expose 3306 port

### ISSUE THREAD

**Issue by Sean2525** [iyear/E5SubBot#5]
Hello
目前的yml是把mysql映射到主機3306 port上
因此主機是public IP的話 有很大的機會受到攻擊 
可以把ports(L5-L6)刪掉, 只要config的host是使用mysql容器名稱連接就不會有問題

https://github.com/iyear/E5SubBot/blob/9cf10dcf35a8409a8741bbf5b54b783f913b23a6/docker-compose.yml#L3-L14

**Comment by iyear** [comment]
刚回家现在才合并，感谢！
