### ISSUE TITLE
考不考虑添加英文版？

### ISSUE THREAD

**Issue by ifvv** [iyear/E5SubBot#9]
![image](https://user-images.githubusercontent.com/57923430/84082858-24fecb80-aa13-11ea-8c51-da00203db9b9.png)
感觉也有很多外国人在使用这个telebot...但是他们看不懂中文

**Comment by iyear** [comment]
@ifvv 很多老外有用?……真的要加也要等等了，学习太忙了

**Comment by iyear** [comment]
已添加英文版README，暂无bot内置英文计划
